### PR TITLE
sprites: new projectile for Blood Sceptre by Talon1024

### PR DESCRIPTION
**Pull request by GeorgePieVG**
Originally proposed here: Blasphemer/blasphemer#29

### CODE REVIEW

**Comment by Talon1024** [comment]
Why did you close this?

**Comment by GeorgePieVG** [comment]
> Why did you close this?

Conflicts with the main branch. Need to be resolved first. I also already [suggested](https://www.doomworld.com/forum/post/2823352) adding your projectiles on Doomworld, maybe they will be added in the next version.

**Comment by GeorgePieVG** [comment]
By the way, I was wondering if [this necrocannon replacement](https://github.com/Blasphemer/blasphemer/pull/28) was taken from Hell Forged or Demon Eclipse? Because I didn't find it in hell forged. If it's from Demon Eclipse, it can still be used in Blasphemer and it looks really good.

**Comment by Talon1024** [comment]
All right, I'll submit a new pull request to this repo, hopefully without any merge conflicts.

As for the necrocannon replacement, it's from DEHEv01.wad, and I don't know if that version of Demon Eclipse has a license compatible with Blasphemer, so I figured it's best to be on the safe side and close it for now.

**Comment by GeorgePieVG** [comment]
> All right, I'll submit a new pull request to this repo, hopefully without any merge conflicts.
> 
> As for the necrocannon replacement, it's from [DEHEv01.wad](https://forum.zdoom.org/viewtopic.php?p=940559#p940559), and I don't know if that version of Demon Eclipse has a license compatible with Blasphemer (CC-BY is not compatible according to CONTRIBUTING.md). In addition, that version of Demon Eclipse has a lot of stuff that's still in today's release of Hell-Forged, so I figured it's best to be on the safe side and close it for now.

Awesome stuff, thanks for the link! Yes, CC-BY is incompatible with Blasphemer, however Amuscaria has given permission to use resources from Demon Eclipse in Freedoom and Blasphemer. And probably all the guns except the golden wand and frostfang were already taken from DE. So I think you can resubmit necrocannon as well.  And finally, I suggest you join [this Discord server](https://discord.gg/M7jhmw9zn4) and share your contributions there, that's where development is most active.

**Comment by GeorgePieVG** [comment]
> EDIT: I searched the thread. It looks like the first version of those sprites [came out in 2014](https://forum.zdoom.org/viewtopic.php?p=743537&hilit=Basilisk#p743537), and permission to use Demon Eclipse resources in GZDoom, Freedoom, and other projects was [given in 2012](https://forum.zdoom.org/viewtopic.php?f=42&t=13397&p=642078#p642078).

Sorry for the necrobump, but I recently decided to check one thing out. The first mentions of the new guardian cube design used in Freedoom as a replacement for the boss spawn cube [date back to March 2013](https://forum.zdoom.org/viewtopic.php?p=676301#p676301). Also, I found a [few](https://www.moddb.com/games/doom/addons/demon-eclipse-hell-forge-edition-beta-08) [other](https://forum.zdoom.org/viewtopic.php?f=19&t=46877) Demon Eclipse resource packs, but none of them except yours have the explosion sprites that were also used in Freedoom. Maybe a new permission was given?

**Pull request closed without merging**
